[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "point-cloud-inference"
version = "0.2.0"
description = "PointNet inference on point cloud data."

requires-python = ">=3.9"

dependencies = [
    "tqdm==4.67.1"
]

[tool.setuptools]
package-dir = {"" = "inference_src"}

[tool.setuptools.packages.find]
where = ["inference_src"]



[project.urls]
Homepage = "https://github.com/dlrgroupcomputationaldesign/DLR_Pointnet_Pointnet2_pytorch"
